name: myapp
description: Attendance Management System

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # UI and theming
  google_fonts: ^6.1.0
  shimmer: ^3.0.0

  # Navigation
  go_router: ^16.3.0

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # File operations - using a more compatible version
  file_picker: ^10.3.3

  # CSV handling
  csv: ^6.0.0

  # Sharing functionality
  share_plus: ^12.0.1

  # URL launching
  url_launcher: ^6.2.2

  # Path provider for file system access
  path_provider: ^2.1.2

  # Permissions
  permission_handler: ^12.0.1

  # Shared preferences for storing user settings
  shared_preferences: ^2.2.2

  # Firebase packages required for invite flows
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  cloud_functions: ^5.6.2
  firebase_dynamic_links: ^6.1.10
  uuid: ^4.0.7

  # Crypto for sha256 hashing when creating invite fallback locally
  crypto: ^3.0.2

  # Connectivity detection for background retry of pending profiles
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.3.6
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/LOGO.png"
  adaptive_icon_background: "assets/LOGO.png"
  adaptive_icon_foreground: "assets/LOGO.png"

flutter:
  uses-material-design: true

  # Assets for sample data
  assets:
    - assets/sample_data/
    - assets/fox.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the locations of the font files to use for that family.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
