// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEfslpoubBotVC0PNhx2v3kYduOOlWVTo',
    appId: '1:569095362549:web:36a015f9d7c7067970b2bc',
    messagingSenderId: '569095362549',
    projectId: 'attendance-b9f1a',
    authDomain: 'attendance-b9f1a.firebaseapp.com',
    storageBucket: 'attendance-b9f1a.firebasestorage.app',
    measurementId: 'G-KRHHB3Z3M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9goxTaph5WZy8uvY5F_nIBVcVOI7B10I',
    appId: '1:569095362549:android:1d83cce5caf8f4ed70b2bc',
    messagingSenderId: '569095362549',
    projectId: 'attendance-b9f1a',
    storageBucket: 'attendance-b9f1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8cgn7p9YMFNB7BvdnX6RgOC_VIGPBsLY',
    appId: '1:569095362549:ios:4d37b150709d7e7f70b2bc',
    messagingSenderId: '569095362549',
    projectId: 'attendance-b9f1a',
    storageBucket: 'attendance-b9f1a.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8cgn7p9YMFNB7BvdnX6RgOC_VIGPBsLY',
    appId: '1:569095362549:ios:4d37b150709d7e7f70b2bc',
    messagingSenderId: '569095362549',
    projectId: 'attendance-b9f1a',
    storageBucket: 'attendance-b9f1a.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEfslpoubBotVC0PNhx2v3kYduOOlWVTo',
    appId: '1:569095362549:web:ee0ffdace9b0c6f570b2bc',
    messagingSenderId: '569095362549',
    projectId: 'attendance-b9f1a',
    authDomain: 'attendance-b9f1a.firebaseapp.com',
    storageBucket: 'attendance-b9f1a.firebasestorage.app',
    measurementId: 'G-V4WSYNLJRS',
  );

}