import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show kDebugMode;
import 'package:firebase_auth/firebase_auth.dart' as fb_auth;
import 'package:cloud_functions/cloud_functions.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_dynamic_links/firebase_dynamic_links.dart';
import 'firebase_options.dart';
import 'providers/student_provider.dart';
import 'providers/attendance_provider.dart';
import 'providers/report_provider.dart';
import 'providers/theme_provider.dart';
import 'providers/settings_provider.dart';
import 'providers/auth_provider.dart';
import 'providers/user_provider.dart';
import 'services/router.dart';
import 'services/navigation_service.dart';
import 'services/app_lifecycle_notifier.dart';
import 'services/auth_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with options generated by FlutterFire CLI
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Environment selection: pass --dart-define=ENV=prod for production builds.
  const String env = String.fromEnvironment('ENV', defaultValue: 'prod'); // 'dev' or 'prod'

  // Production: enable Firebase backend and use Firebase Auth via AuthService.
  if (env == 'prod') {
    try {
      AuthService.instance.useFirebase = true;
    } catch (_) {}
  }

  // Development: when explicitly running a dev build and in debug mode, wire
  // to the local Firebase emulators. This keeps existing emulator behavior.
  if (env == 'dev' && kDebugMode) {
    try {
      const String defaultEmuHost = String.fromEnvironment('EMULATOR_HOST', defaultValue: '10.0.2.2');
      final emulatorHost = defaultEmuHost;

      // Auth emulator
      fb_auth.FirebaseAuth.instance.useAuthEmulator(emulatorHost, 9099);

      // Firestore emulator
      FirebaseFirestore.instance.useFirestoreEmulator(emulatorHost, 8080);

      // Functions emulator
      FirebaseFunctions.instance.useFunctionsEmulator(emulatorHost, 5001);

      // Use Firebase SDK auth in dev emulator mode as well
      AuthService.instance.useFirebase = true;
    } catch (e) {
      // ignore; if APIs change or emulator not available, app still runs against prod
    }
  }

  final navigationService = NavigationService();
  final appLifecycleNotifier = AppLifecycleNotifier();

  // Restore persisted auth state (if any) before building router so redirects work
  await AuthProvider.instance.initialize();

  // Initialize user provider (loads users/{uid} doc when signed in)
  await UserProvider.instance.initialize();

  final routerConfig = createRouter(
    navigationService: navigationService,
    refreshListenable: appLifecycleNotifier,
  );

  // Handle incoming dynamic links that may carry an invite token. If a token is
  // present, navigate to the accept-invite route with the token as a query param.
  void handleDynamicLink(PendingDynamicLinkData? data) {
    final deepLink = data?.link;
    if (deepLink == null) return;
    final token = deepLink.queryParameters['token'];
    if (token != null && navigationService != null) {
      // Use the router to push to accept-invite with token query param
      // We use the root navigator key attached by the router; navigate after first frame.
      WidgetsBinding.instance.addPostFrameCallback((_) {
        try {
          // Prefer go() on the router if available via the context; fallback to Navigator
          // The router will respect the path and query param mapping we defined.
          routerConfig.go('/accept-invite?token=${Uri.encodeComponent(token)}');
        } catch (_) {
          // ignore navigation errors early in startup
        }
      });
    }
  }

  // Listen for dynamic links (foreground)
  FirebaseDynamicLinks.instance.onLink.listen((event) {
    handleDynamicLink(event);
  }).onError((_) {});

  // Check initial dynamic link
  try {
    final initialLink = await FirebaseDynamicLinks.instance.getInitialLink();
    handleDynamicLink(initialLink);
  } catch (_) {
    // ignore
  }

  runApp(MyApp(
    routerConfig: routerConfig,
    navigationService: navigationService,
    lifecycleNotifier: appLifecycleNotifier,
  ));
}

class MyApp extends StatelessWidget {
  final GoRouter routerConfig;
  final NavigationService navigationService;
  final AppLifecycleNotifier lifecycleNotifier;

  const MyApp({
    super.key,
    required this.routerConfig,
    required this.navigationService,
    required this.lifecycleNotifier,
  });

  // Updated modern palette tuned to the screenshots
  static const _primaryBlue = Color(0xFF3D86FF);
  static const _primaryBlueVariant = Color(0xFF2F6FDD);
  static const _mutedDark = Color(0xFF222232);
  static const _bgLight = Color(0xFFF7F8FA);
  static const _surfaceLight = Color(0xFFFFFFFF);
  static const _danger = Color(0xFFE74C3C);

  ColorScheme _lightScheme() {
    final base = ColorScheme.light(
      primary: _primaryBlue,
      onPrimary: Colors.white,
      secondary: _mutedDark,
      onSecondary: Colors.white,
      surface: _surfaceLight,
      background: _bgLight,
      error: _danger,
    );
    return base.copyWith(
      primaryContainer: _primaryBlueVariant,
      onPrimaryContainer: Colors.white,
      secondaryContainer: const Color(0xFFF1F3F8),
      onSecondaryContainer: _mutedDark,
      onSurface: const Color(0xFF0F1720),
      surfaceContainerHighest: const Color(0xFFF5F7FB),
      outline: const Color(0xFFE6E9F0),
      outlineVariant: const Color(0xFFF1F3F8),
      tertiary: _primaryBlue,
      onTertiary: Colors.white,
      tertiaryContainer: const Color(0xFFEFF5FF),
      onTertiaryContainer: _primaryBlueVariant,
      inverseSurface: const Color(0xFF0F1720),
      onInverseSurface: Colors.white,
      inversePrimary: _primaryBlueVariant,
      scrim: Colors.black54,
      shadow: Colors.black26,
    );
  }

  ColorScheme _darkScheme() {
    final base = ColorScheme.dark(
      primary: _primaryBlue,
      onPrimary: Colors.black,
      secondary: _mutedDark,
      onSecondary: Colors.white,
      surface: const Color(0xFF14141A),
      background: const Color(0xFF0B0B0F),
      error: _danger,
    );
    return base.copyWith(
      primaryContainer: _primaryBlueVariant,
      onPrimaryContainer: Colors.black,
      secondaryContainer: const Color(0xFF1C1C22),
      onSecondaryContainer: Colors.white,
      onSurface: Colors.white,
      surfaceContainerHighest: const Color(0xFF1C1C22),
      outline: const Color(0xFF2A2A30),
      outlineVariant: const Color(0xFF1C1C22),
      tertiary: _primaryBlue,
      onTertiary: Colors.black,
      tertiaryContainer: const Color(0xFF2B3F5F),
      onTertiaryContainer: Colors.white,
      inverseSurface: const Color(0xFFF2F2F2),
      onInverseSurface: const Color(0xFF1E1E1E),
      inversePrimary: _primaryBlueVariant,
      scrim: Colors.black54,
      shadow: Colors.black45,
    );
  }

  ThemeData _baseTheme(ColorScheme scheme) {
    final textTheme = GoogleFonts.poppinsTextTheme();

    // Typography roles tailored to the mockups
    var headlines = textTheme.copyWith(
      headlineSmall: textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w700, fontSize: 20),
      titleLarge: textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w700, fontSize: 22),
      titleMedium: textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w600, fontSize: 16),
      bodyMedium: textTheme.bodyMedium?.copyWith(fontWeight: FontWeight.w400, fontSize: 14),
      labelLarge: textTheme.labelLarge?.copyWith(fontWeight: FontWeight.w600, fontSize: 14),
    );

    // Make sure all text uses the colorScheme's onSurface (or appropriate contrast)
    // so that unstyled Text() widgets remain readable in dark mode.
    headlines = headlines.apply(bodyColor: scheme.onSurface, displayColor: scheme.onSurface);

    return ThemeData(
      useMaterial3: true,
      colorScheme: scheme,
      textTheme: headlines,
      fontFamily: GoogleFonts.poppins().fontFamily,
      scaffoldBackgroundColor: scheme.background,
      appBarTheme: AppBarTheme(
        backgroundColor: scheme.surface,
        foregroundColor: scheme.onSurface,
        elevation: 0,
        centerTitle: true,
        titleTextStyle: headlines.titleLarge?.copyWith(color: scheme.onSurface),
        iconTheme: IconThemeData(color: scheme.onSurface),
      ),
      cardTheme: CardThemeData(
        color: scheme.surface,
        elevation: 6,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        margin: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: scheme.primary,
          foregroundColor: scheme.onPrimary,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
          textStyle: headlines.labelLarge,
          elevation: 6,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          foregroundColor: scheme.onSurface,
          side: BorderSide(color: scheme.outline),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 12),
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: scheme.primary,
        foregroundColor: scheme.onPrimary,
        elevation: 10,
        sizeConstraints: const BoxConstraints(minWidth: 56, minHeight: 56),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: scheme.surfaceContainerHighest,
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: scheme.outline),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: scheme.primary, width: 1.5),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
      ),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: scheme.surface,
        contentTextStyle: headlines.bodyMedium?.copyWith(color: scheme.onSurface),
        behavior: SnackBarBehavior.floating,
      ),
      navigationBarTheme: NavigationBarThemeData(
        backgroundColor: scheme.surface,
        indicatorColor: scheme.primary.withOpacity(0.12),
        elevation: 0,
        iconTheme: WidgetStateProperty.resolveWith((states) {
          final selected = states.contains(WidgetState.selected);
          final color = selected ? scheme.primary : scheme.onSurface.withOpacity(0.6);
          return IconThemeData(color: color);
        }),
        labelTextStyle: WidgetStateProperty.resolveWith((states) {
          final selected = states.contains(WidgetState.selected);
          final color = selected ? scheme.primary : scheme.onSurface.withOpacity(0.6);
          return headlines.labelLarge?.copyWith(color: color, fontSize: 12);
        }),
      ),
      pageTransitionsTheme: const PageTransitionsTheme(
        builders: {
          TargetPlatform.android: CupertinoPageTransitionsBuilder(),
          TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
          TargetPlatform.macOS: CupertinoPageTransitionsBuilder(),
          TargetPlatform.windows: CupertinoPageTransitionsBuilder(),
          TargetPlatform.linux: CupertinoPageTransitionsBuilder(),
        },
      ),
      visualDensity: VisualDensity.adaptivePlatformDensity,
    );
  }

  ThemeData _buildLightTheme() => _baseTheme(_lightScheme());
  ThemeData _buildDarkTheme() => _baseTheme(_darkScheme());

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => SettingsProvider()),
        ChangeNotifierProvider(create: (_) => StudentProvider()),
        ChangeNotifierProvider(create: (_) => AttendanceProvider()),
        ChangeNotifierProvider(create: (_) => ReportProvider()),
        ChangeNotifierProvider(create: (_) => UserProvider.instance),
        Provider<NavigationService>.value(value: navigationService),
        ChangeNotifierProvider<AppLifecycleNotifier>.value(value: lifecycleNotifier),
      ],
      child: Consumer<ThemeProvider>(
        builder: (context, themeProvider, child) {
          final themeMode = themeProvider.themeMode;

          return MaterialApp.router(
            title: 'Attendance Management System',
            theme: _buildLightTheme(),
            darkTheme: _buildDarkTheme(),
            themeMode: themeMode,
            routerConfig: routerConfig,
            debugShowCheckedModeBanner: false,
            restorationScopeId: 'app',
          );
        },
      ),
    );
  }
}
