name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Android artifacts
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

<<<<<<< HEAD
      - name: "Setup Java 17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
      - name: "Flutter version"
        run: |
          flutter --version
          java -version

=======
      - name: "Install JDK 11"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openjdk-11-jdk
          java -version

      - name: "Install Flutter (manual, pinned)"
        run: |
          set -eux
          FLUTTER_VERSION=3.10.6
          ARCHIVE=flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
          URL="https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/${ARCHIVE}"
          echo "Downloading Flutter ${FLUTTER_VERSION} from ${URL}"
          sudo apt-get update -y
          sudo apt-get install -y xz-utils unzip curl ca-certificates
          curl -fsSL -o /tmp/${ARCHIVE} "${URL}"
          tar -xJf /tmp/${ARCHIVE} -C $HOME
          # Ensure flutter binary available at $HOME/flutter/bin/flutter
          echo "PATH=$HOME/flutter/bin:$PATH" >> $GITHUB_ENV
          $HOME/flutter/bin/flutter --version
          $HOME/flutter/bin/flutter precache --android || true

      - name: "Diagnostic: show flutter/java versions and PATH"
        run: |
          echo '--- flutter --version ---'
          flutter --version || true
          echo '--- java -version ---'
          java -version || true
          echo '--- which flutter ---'
          which flutter || true
          echo '--- PATH ---'
          echo $PATH

>>>>>>> 9118324dd5ef2cbba5cfeb15d5c3b064d2db1e5c
      - name: "Install dependencies"
        run: flutter pub get

      - name: "Run analyzer (optional)"
        run: flutter analyze || true

      - name: "Build Android APK (release)"
        run: flutter build apk --release

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            build/app/outputs/flutter-apk/*.apk

      - name: "Create GitHub Release"
<<<<<<< HEAD
        if: github.event_name == 'push'
=======
>>>>>>> 9118324dd5ef2cbba5cfeb15d5c3b064d2db1e5c
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.run_number }}
          release_name: "Automated build ${{ github.run_number }}"
          body: "Automated Android build from commit ${{ github.sha }}"
          draft: false
          prerelease: false

      - name: "Upload APK to Release"
<<<<<<< HEAD
        if: github.event_name == 'push'
=======
>>>>>>> 9118324dd5ef2cbba5cfeb15d5c3b064d2db1e5c
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive

      # Note: Google Play publish step removed. Use Releases for internal distribution.
