name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    name: Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Run analyzer
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage

  functions-deploy-preview:
    name: Functions lint/test (optional)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install functions deps
        working-directory: functions
        run: npm ci
      - name: TypeScript build
        working-directory: functions
        run: npm run build
      - name: Run functions tests (rules unit tests)
        working-directory: functions
        run: npx mocha -r ts-node/register tests/**/*.test.ts || true

